ANCHORS:
 node_steps: &node_steps
   steps:
     - checkout
     - run: npm install
     - run: npm test
     # Check whether "run build" is successful
     - run: npm run build

version: 2
jobs:
  node_10:
    docker:
      - image: node:10-alpine 
    <<: *node_steps
  
  node_8:
    docker:
      - image: node:8-alpine 
    <<: *node_steps
  
  docker_test:
    machine: true
    steps:
      - checkout
      # Check whether "docker build" is succcessful or not
      - run: docker build -t piping-server .
      - run:
          name: Working test with Docker image
          command: |
            # Run a server
            docker run -d -p 8080:8080 piping-server
            # Wait for server running
            sleep 1
            # Send and wait for a reciever
            curl --data-binary 'hello, world' localhost:8080/mypath &
            # Get data
            curl localhost:8080/mypath

  # (from: https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/)
  npm_publish:
    docker:
    - image: node:10-alpine
    steps:
      - checkout
      - run: npm install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > /root/.npmrc
      - run: npm publish

workflows:
  version: 2
  node_tests:
    jobs:
      - node_10
      - node_8
      - docker_test
      - npm_publish:
          requires:
            - node_10
            - node_8
